/*
  # Complete Database Schema for Servet Dekorasyon

  1. New Tables
    - `services` - Service offerings (Banyo Tadilatı, Dekorasyon, etc.)
    - `references` - Project references and portfolio items
    - `blog_posts` - Blog articles and content
    - `contacts` - Contact form submissions
    - `admin_users` - Admin panel users

  2. Security
    - Enable RLS on all tables
    - Add appropriate policies for public read access
    - Admin-only policies for write operations

  3. Sample Data
    - Insert default services
    - Insert sample references
    - Insert sample blog posts
*/

-- Create services table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon TEXT NOT NULL DEFAULT 'Bath',
    order_index INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.services 
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.services 
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.services 
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Create references table
CREATE TABLE IF NOT EXISTS public.references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.references ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.references 
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.references 
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.references 
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Create blog_posts table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Genel',
    author TEXT NOT NULL DEFAULT 'Servet Dekorasyon',
    published BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for published posts" ON public.blog_posts 
    FOR SELECT USING (published = true);

CREATE POLICY "Enable all access for authenticated users" ON public.blog_posts 
    FOR ALL USING (auth.role() = 'authenticated');

-- Create contacts table
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    project_type TEXT,
    budget_range TEXT,
    timeline TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for all users" ON public.contacts 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read for authenticated users only" ON public.contacts 
    FOR SELECT USING (auth.role() = 'authenticated');

-- Create admin_users table
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for authenticated users only" ON public.admin_users 
    FOR SELECT USING (auth.role() = 'authenticated');

-- Insert default services
INSERT INTO public.services (title, description, icon, order_index) VALUES
('Banyo Tadilatı', 'Modern ve fonksiyonel banyo tasarımları ile hayalinizdeki banyoyu gerçeğe dönüştürüyoruz. Vitra ve Artema ürünleri ile kaliteli çözümler sunuyoruz.', 'Bath', 1),
('Dekorasyon', 'Yaşam alanlarınızı estetik ve kullanışlı dekorasyon çözümleriyle yeniliyoruz. Modern tasarım anlayışı ile fonksiyonelliği birleştiriyoruz.', 'Palette', 2),
('Sıhhi Tesisat', 'Profesyonel sıhhi tesisat hizmetleri ile su ve ısıtma sistemlerinizi güvence altına alıyoruz. 24/7 acil servis desteği sağlıyoruz.', 'Wrench', 3)
ON CONFLICT DO NOTHING;

-- Insert sample references
INSERT INTO public.references (image_url, title, description) VALUES
('https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Modern Banyo Tasarımı', 'Vitra ürünleri ile modern ve şık banyo tasarımı. Minimalist yaklaşım ve fonksiyonel çözümler.'),
('https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800', 'Lüks Banyo Dekorasyonu', 'Artema armatürleri ile lüks banyo dekorasyonu. Premium malzemeler ve özel tasarım.'),
('https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800', 'Kompakt Banyo Çözümü', 'Küçük alanlarda maksimum verimlilik. Akıllı depolama ve çok fonksiyonlu tasarım.'),
('https://images.pexels.com/photos/1571467/pexels-photo-1571467.jpeg?auto=compress&cs=tinysrgb&w=800', 'Klasik Banyo Tasarımı', 'Zamansız elegans ve fonksiyonellik. Geleneksel tarzda modern dokunuşlar.'),
('https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=800', 'Spa Konsepti Banyo', 'Evde spa deneyimi. Rahatlatıcı atmosfer ve lüks detaylar.'),
('https://images.pexels.com/photos/1454804/pexels-photo-1454804.jpeg?auto=compress&cs=tinysrgb&w=800', 'Endüstriyel Tarz Banyo', 'Modern endüstriyel tasarım. Ham malzemeler ve çağdaş çizgiler.')
ON CONFLICT DO NOTHING;

-- Insert sample blog posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, image_url, category, author) VALUES
('2024 Banyo Tasarım Trendleri', '2024-banyo-tasarim-trendleri', 'Bu yıl banyo tasarımında öne çıkan trendler ve modern çözümler hakkında detaylı rehber.', '<h2>2024 Yılının En Popüler Banyo Tasarım Trendleri</h2><p>Banyo tasarımı, ev dekorasyonunun en önemli alanlarından biri haline geldi. 2024 yılında öne çıkan trendler, hem estetik hem de fonksiyonellik açısından çığır açıcı yenilikler sunuyor.</p><h3>Minimalist Tasarım</h3><p>Sadelik ve işlevselliğin ön planda olduğu minimalist banyo tasarımları, 2024''ün en güçlü trendi. Temiz çizgiler, nötr renkler ve gereksiz detaylardan arınmış tasarımlar tercih ediliyor.</p>', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tasarım', 'Servet Dekorasyon'),
('Küçük Banyolar İçin Büyük Fikirler', 'kucuk-banyolar-icin-buyuk-fikirler', 'Sınırlı alanları maksimum verimlilikle kullanmanın püf noktaları ve yaratıcı çözümler.', '<h2>Küçük Banyo Alanlarını Verimli Kullanma Rehberi</h2><p>Küçük banyo alanları, doğru tasarım yaklaşımıyla büyük banyolar kadar fonksiyonel ve şık olabilir. İşte size ilham verecek fikirler...</p><h3>Dikey Alan Kullanımı</h3><p>Duvarları maksimum verimlilikle kullanarak depolama alanı yaratın. Yüksek dolaplar ve raflar, zemin alanından tasarruf sağlar.</p>', 'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800', 'İpuçları', 'Servet Dekorasyon'),
('Vitra vs Artema: Hangisi Daha İyi?', 'vitra-vs-artema-karsilastirma', 'İki büyük markanın ürünlerini detaylı karşılaştırıyoruz. Kalite, fiyat ve tasarım açısından analiz.', '<h2>Vitra ve Artema Markalarının Detaylı Karşılaştırması</h2><p>Banyo sektörünün iki dev markası Vitra ve Artema, her biri kendine özgü avantajları ile öne çıkıyor. Bu yazımızda her iki markayı detaylı olarak inceliyoruz.</p><h3>Kalite ve Dayanıklılık</h3><p>Her iki marka da yüksek kalite standartlarına sahip. Vitra''nın porselen kalitesi, Artema''nın ise armatür teknolojisi öne çıkıyor.</p>', 'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800', 'Ürün İnceleme', 'Servet Dekorasyon')
ON CONFLICT DO NOTHING;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_services_order ON public.services(order_index);
CREATE INDEX IF NOT EXISTS idx_references_created_at ON public.references(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON public.blog_posts(published, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON public.blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON public.contacts(created_at DESC);